### ISSUE TITLE
Error when creating a new blog

### ISSUE THREAD

**Issue by pakjiddat** [alxshelepenok/gatsby-starter-lumen#967] opened 2021-07-21 11:22 UTC
I get the following error when running the command:

`gatsby new blog https://github.com/alxshelepenok/gatsby-starter-lumen`

```
nadir@nadir-X551MA:~/Projects$ gatsby new pakjiddat https://github.com/alxshelepenok/gatsby-starter-lumen
info Creating new site from git:
https://github.com/alxshelepenok/gatsby-starter-lumen.git

Cloning into 'pakjiddat'...
remote: Enumerating objects: 340, done.
remote: Counting objects: 100% (340/340), done.
remote: Compressing objects: 100% (271/271), done.
remote: Total 340 (delta 47), reused 298 (delta 43), pack-reused 0
Receiving objects: 100% (340/340), 4.89 MiB | 510.00 KiB/s, done.
success Created starter directory layout
info Installing packages...
info Preferred package manager set to "npm"

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: gatsby-starter-lumen@3.0.7
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!   peer react@"^16.4.2 || ^17.0.0" from gatsby-link@2.11.0
npm ERR!   node_modules/gatsby-link
npm ERR!     gatsby-link@"^2.11.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"15.x || 16.x || 16.4.0-alpha.0911da3" from @reach/router@1.3.4
npm ERR! node_modules/@reach/router
npm ERR!   peer @reach/router@"^1.3.3" from gatsby-link@2.11.0
npm ERR!   node_modules/gatsby-link
npm ERR!     gatsby-link@"^2.11.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/nadir/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:

ERROR 

Command failed with exit code 1: npm install

  Error: Command failed with exit code 1: npm install
  
  - error.js:60 makeError
    [lib]/[gatsby-cli]/[execa]/lib/error.js:60:11
  
  - index.js:118 handlePromise
    [lib]/[gatsby-cli]/[execa]/index.js:118:26
  
  - task_queues.js:95 processTicksAndRejections
    internal/process/task_queues.js:95:5
  
  - init-starter.js:135 install
    [lib]/[gatsby-cli]/lib/init-starter.js:135:7
  
  - init-starter.js:202 clone
    [lib]/[gatsby-cli]/lib/init-starter.js:202:3
  
  - init-starter.js:343 initStarter
    [lib]/[gatsby-cli]/lib/init-starter.js:343:5
  
  - create-cli.js:494 
    [lib]/[gatsby-cli]/lib/create-cli.js:494:9

```

**Desktop Details:**

 - OS: Ubuntu 20.0.4
 - Browser: Chromium
 - Version: 91
 - node.js: v14.17.3
 - npm: v7.20.0
 - gatsby-cli: v3.10.0

**Comment by brandongregoryscott** [comment] 2021-07-24 18:49
Looks like a duplicate of #887 - I ran into the same thing, and running `npm i --legacy-peer-deps` forced it to install/start up.

**Comment by alxshelepenok** [comment] 2022-04-16 15:45
Thank you for your feedback. The starter has been updated to the new version and the bug has probably been fixed. Feel free to reopen the issue.

**Closed by alxshelepenok** 2022-04-16 15:45 UTC
